export const COUNTRY_CODES = [
  { code: "+55", label: "🇧🇷 Brasil (+55)" },
  { code: "+1", label: "🇺🇸/🇨🇦 EUA/Canadá (+1)" },
  { code: "+351", label: "🇵🇹 Portugal (+351)" },
  { code: "+244", label: "🇦🇴 Angola (+244)" },
  { code: "+258", label: "🇲🇿 Moçambique (+258)" },
  { code: "+238", label: "🇨🇻 Cabo Verde (+238)" },
  { code: "+54", label: "🇦🇷 Argentina (+54)" },
  { code: "+56", label: "🇨🇱 Chile (+56)" },
  { code: "+57", label: "🇨🇴 Colômbia (+57)" },
  { code: "+51", label: "🇵🇪 Peru (+51)" },
  { code: "+52", label: "🇲🇽 México (+52)" },
  { code: "+598", label: "🇺🇾 Uruguai (+598)" },
  { code: "+595", label: "🇵🇾 Paraguai (+595)" },
  { code: "+591", label: "🇧🇴 Bolívia (+591)" },
  { code: "+58", label: "🇻🇪 Venezuela (+58)" },
  { code: "+593", label: "🇪🇨 Equador (+593)" },
  { code: "+34", label: "🇪🇸 Espanha (+34)" },
  { code: "+44", label: "🇬🇧 Reino Unido (+44)" },
  { code: "+49", label: "🇩🇪 Alemanha (+49)" },
  { code: "+33", label: "🇫🇷 França (+33)" },
  { code: "+39", label: "🇮🇹 Itália (+39)" },
  { code: "+41", label: "🇨🇭 Suíça (+41)" },
  { code: "+353", label: "🇮🇪 Irlanda (+353)" },
  { code: "+31", label: "🇳🇱 Holanda (+31)" },
  { code: "+32", label: "🇧🇪 Bélgica (+32)" },
  { code: "+81", label: "🇯🇵 Japão (+81)" },
  { code: "+86", label: "🇨🇳 China (+86)" },
  { code: "+91", label: "🇮🇳 Índia (+91)" },
  { code: "+61", label: "🇦🇺 Austrália (+61)" },
  { code: "+64", label: "🇳🇿 Nova Zelândia (+64)" },
  { code: "+971", label: "🇦🇪 EAU (+971)" },
];
